#pragma once
#ifndef FREEZEVERB_MODULE_H
#define FREEZEVERB_MODULE_H

// ===========================================================================
// freezeverb_module.h  — GENERATED by make_effect.py. Do not hand-edit.
// ---------------------------------------------------------------------------
// Self-contained per-effect wrapper, PIMPL shape (RNBO out of the header, only
// forward-declared), so this can sit next to q-using modules in
// loaded_effects.h without the fast-math symbol clash. RNBO access lives in
// freezeverb_module.cpp.
// ===========================================================================

#include <stdint.h>
#include "base_effect_module.h"

#ifdef __cplusplus

namespace RNBO {
    template <class ENGINE> class FreezeVerb;
}

namespace bkshepherd {

class FreezeVerbModule : public BaseEffectModule {
  public:
    // kshep-side param SLOTS (not RNBO indices). RNBO index for each is
    // discovered by name at Init(). Order matches s_metaData + s_paramNames.
    enum Param {
        DECAY = 0,
        REVERB_AMT = 1,
        LP = 2,
        CHORUS_AMT = 3,
        FLUTTER_SPD = 4,
        DEGRADATION_AMT = 5,
        DEGRADATION_SPD = 6,
        PARAM_COUNT
    };

    FreezeVerbModule();
    ~FreezeVerbModule();

    void Init(float sample_rate) override;
    void ProcessMono(float in) override;
    void ProcessStereo(float inL, float inR) override;
    float GetBrightnessForLED(int led_id) const override;
    void SetFootswitch(int fsw_id, float value) override;

    bool UsesRawFootswitch1() const override { return true; }

  private:
    static constexpr int kBlockSize = 48; // must match guitar_pedal.cpp blockSize

    int m_fsw1Index = -1;
    int m_fsw2Index = -1;
    int m_led1Index = -1;
    int m_led2Index = -1;

    int m_paramIndex[PARAM_COUNT];

    volatile float m_fsw1Value = 0.0f;
    volatile float m_fsw2Value = 0.0f;
    volatile float m_led1Value = 0.0f;
    volatile float m_led2Value = 0.0f;

    float m_inL[kBlockSize];
    float m_inR[kBlockSize];
    float m_outL[kBlockSize];
    float m_outR[kBlockSize];
    int m_bufferIndex;

    struct Impl;
    Impl *m_impl;

    void ProcessAudioBlock(int size);
};

} // namespace bkshepherd
#endif // __cplusplus
#endif // FREEZEVERB_MODULE_H
