// ===========================================================================
// freezeverb_module.cpp  — GENERATED by make_effect.py. Do not hand-edit.
// ---------------------------------------------------------------------------
// The ONE translation unit where RNBO is included. `q` must never be included
// here. Modeled on the proven freezeverb v12 wrapper, generalized from
// hardcoded knobs to a loop over the discovered param table.
// ===========================================================================

#include "freezeverb_module.h"
#include <string.h> // strcmp for param-name discovery

// RNBO export, native filename ("<classname>.cpp.h"). Sits at
// dependencies/RNBO/freezeverb.cpp.h.
#include "freezeverb.cpp.h"

using namespace bkshepherd;

struct FreezeVerbModule::Impl {
    RNBO::FreezeVerb<> rnbo;
    RNBO::SampleValue *in[2];
    RNBO::SampleValue *out[2];
};

// Exact RNBO param names, in Param-enum slot order.
static const char *s_paramNames[FreezeVerbModule::PARAM_COUNT] = {
    "decay",
    "reverb_amt",
    "lp",
    "chorus_amt",
    "flutter_spd",
    "degradation_amt",
    "degradation_spd"
};

// kshep parameter metadata, same slot order. Labels from RNBO names; defaults
// from description.json initialValue; no MIDI CC yet (-1).
static const ParameterMetaData s_metaData[FreezeVerbModule::PARAM_COUNT] = {
    {
        name : "decay",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {.float_value = 0.7f},
        knobMapping : 0,
        midiCCMapping : -1
    },
    {
        name : "reverb amt",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {.float_value = 0.5f},
        knobMapping : 1,
        midiCCMapping : -1
    },
    {
        name : "lp",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {.float_value = 0.7f},
        knobMapping : 2,
        midiCCMapping : -1
    },
    {
        name : "chorus amt",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {.float_value = 1.0f},
        knobMapping : 3,
        midiCCMapping : -1
    },
    {
        name : "flutter spd",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {.float_value = 1.0f},
        knobMapping : 4,
        midiCCMapping : -1
    },
    {
        name : "degradation amt",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {.float_value = 0.02f},
        knobMapping : 5,
        midiCCMapping : -1
    },
    {
        name : "degradation spd",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {.float_value = 0.01f},
        knobMapping : -1,
        midiCCMapping : -1
    }
};

FreezeVerbModule::FreezeVerbModule() : BaseEffectModule(), m_bufferIndex(0), m_impl(nullptr) {
    m_name = "FreezeVerb";

    m_paramMetaData = s_metaData;
    InitParams(FreezeVerbModule::PARAM_COUNT);

    for (int i = 0; i < FreezeVerbModule::PARAM_COUNT; ++i) {
        m_paramIndex[i] = -1;
    }
    // RNBO object deferred to Init() (module ctors run before hardware/heap up).
}

FreezeVerbModule::~FreezeVerbModule() {
    delete m_impl;
}

void FreezeVerbModule::Init(float sample_rate) {
    BaseEffectModule::Init(sample_rate);

    m_bufferIndex = 0;
    for (int i = 0; i < kBlockSize; ++i) {
        m_inL[i] = 0.0f;
        m_inR[i] = 0.0f;
        m_outL[i] = 0.0f;
        m_outR[i] = 0.0f;
    }

    if (m_impl == nullptr) {
        m_impl = new Impl();
        m_impl->in[0] = m_inL;
        m_impl->in[1] = m_inR;
        m_impl->out[0] = m_outL;
        m_impl->out[1] = m_outR;
    }

    m_impl->rnbo.initialize();
    m_impl->rnbo.prepareToProcess(sample_rate, kBlockSize, true);

    m_fsw1Index = m_fsw2Index = m_led1Index = m_led2Index = -1;
    for (int i = 0; i < FreezeVerbModule::PARAM_COUNT; ++i) {
        m_paramIndex[i] = -1;
    }

    const RNBO::ParameterIndex n = m_impl->rnbo.getNumParameters();
    for (RNBO::ParameterIndex i = 0; i < n; ++i) {
        const char *pname = m_impl->rnbo.getParameterName(i);
        if (pname == nullptr) {
            continue;
        }
        if (strcmp(pname, "fsw1") == 0) {
            m_fsw1Index = (int)i;
        } else if (strcmp(pname, "fsw2") == 0) {
            m_fsw2Index = (int)i;
        } else if (strcmp(pname, "led1") == 0) {
            m_led1Index = (int)i;
        } else if (strcmp(pname, "led2") == 0) {
            m_led2Index = (int)i;
        } else {
            for (int k = 0; k < FreezeVerbModule::PARAM_COUNT; ++k) {
                if (strcmp(pname, s_paramNames[k]) == 0) {
                    m_paramIndex[k] = (int)i;
                    break;
                }
            }
        }
    }

    for (int k = 0; k < FreezeVerbModule::PARAM_COUNT; ++k) {
        if (m_paramIndex[k] >= 0) {
            m_impl->rnbo.setParameterValue(m_paramIndex[k], GetParameterAsFloat(k), RNBO::TimeNow);
        }
    }
}

void FreezeVerbModule::ProcessAudioBlock(int size) {
    for (int k = 0; k < FreezeVerbModule::PARAM_COUNT; ++k) {
        if (m_paramIndex[k] >= 0) {
            m_impl->rnbo.setParameterValue(m_paramIndex[k], GetParameterAsFloat(k), RNBO::TimeNow);
        }
    }

    if (m_fsw1Index >= 0) {
        m_impl->rnbo.setParameterValue(m_fsw1Index, m_fsw1Value, RNBO::TimeNow);
    }
    if (m_fsw2Index >= 0) {
        m_impl->rnbo.setParameterValue(m_fsw2Index, m_fsw2Value, RNBO::TimeNow);
    }

    m_impl->rnbo.process(m_impl->in, 2, m_impl->out, 2, (RNBO::Index)size);

    if (m_led1Index >= 0) {
        m_led1Value = (float)m_impl->rnbo.getParameterValue(m_led1Index);
    }
    if (m_led2Index >= 0) {
        m_led2Value = (float)m_impl->rnbo.getParameterValue(m_led2Index);
    }
}

void FreezeVerbModule::SetFootswitch(int fsw_id, float value) {
    if (fsw_id == 0) {
        m_fsw1Value = value;
    } else if (fsw_id == 1) {
        m_fsw2Value = value;
    }
}

void FreezeVerbModule::ProcessStereo(float inL, float inR) {
    if (m_impl == nullptr) {
        m_audioLeft = inL;
        m_audioRight = inR;
        return;
    }

    m_inL[m_bufferIndex] = inL;
    m_inR[m_bufferIndex] = inR;

    m_audioLeft = m_outL[m_bufferIndex];
    m_audioRight = m_outR[m_bufferIndex];

    ++m_bufferIndex;
    if (m_bufferIndex >= kBlockSize) {
        ProcessAudioBlock(kBlockSize);
        m_bufferIndex = 0;
    }
}

void FreezeVerbModule::ProcessMono(float in) {
    ProcessStereo(in, in);
}

float FreezeVerbModule::GetBrightnessForLED(int led_id) const {
    if (m_impl != nullptr) {
        if (led_id == 0 && m_led1Index >= 0) {
            return m_led1Value;
        }
        if (led_id == 1 && m_led2Index >= 0) {
            return m_led2Value;
        }
    }
    return BaseEffectModule::GetBrightnessForLED(led_id);
}
