#!/usr/bin/env python3
"""
make_effect.py — RNBO-on-kshep effect generator
STAGE 2 (v1): MODULE-FILE GENERATOR.

Reads an RNBO export's description.json and writes a self-contained pair of
wrapper files, modeled directly on the proven v12 freezeverb wrapper:

    <out>/<snake>_module.h
    <out>/<snake>_module.cpp

Design (matches v12 exactly, generalized from 3 hardcoded knobs to a loop):
  - PIMPL: RNBO is included ONLY in the .cpp, behind an opaque Impl*. The header
    forward-declares the RNBO type. This is what keeps RNBO out of any
    translation unit shared with the `q` library.
  - RNBO constructed in Init() (deferred), never in the constructor.
  - Params discovered BY NAME at Init() (scan getNumParameters/getParameterName),
    so physical index order in the export doesn't matter.
  - Reserved names fsw1/fsw2/led1/led2 -> footswitches/LEDs, excluded from knobs.
  - Non-reserved params -> knobs (first 6, by @order) then menu (-1 knobMapping).
  - Params pushed into RNBO once per block (unconditional), like v12.
  - LED values cached in the audio thread, returned by the const LED getter.

Usage:
    python make_effect_modulegen_v1.py <export_folder> <out_folder> [Name] [snake]

    <export_folder> holds description.json
    <out_folder>    where the two files are written (created if missing)
    [Name]          class stem (e.g. FreezeVerb); default from meta.rnboobjname
    [snake]         file stem (e.g. freezeverb);  default from meta.name

Writes nothing except the two files in <out_folder>. Never touches the project.
"""

import sys
import os
import json

RESERVED = {"fsw1", "fsw2", "led1", "led2"}
MAX_KNOBS = 6
MAX_MENU = 10


# ---------------------------------------------------------------------------
# parse + classify (same logic proven in Stage 1)
# ---------------------------------------------------------------------------
def load_description(export_folder):
    path = os.path.join(export_folder, "description.json")
    if not os.path.isfile(path):
        sys.exit(f"ERROR: no description.json in {export_folder!r}")
    with open(path, "r") as f:
        return json.load(f)


def classify(params):
    non_reserved = [p for p in params if p["name"] not in RESERVED]
    non_reserved.sort(key=lambda p: (p["order"], p["index"]))
    knobs = non_reserved[:MAX_KNOBS]
    menu = non_reserved[MAX_KNOBS:MAX_KNOBS + MAX_MENU]
    overflow = non_reserved[MAX_KNOBS + MAX_MENU:]
    return non_reserved, knobs, menu, overflow


def clean_label(rnbo_name):
    """reverb_time -> 'reverb time'. Underscores to spaces, case left untouched
    (whatever you named the param in the patch is what shows on screen)."""
    return rnbo_name.replace("_", " ")


LABEL_WARN_LEN = 12  # kshep screen truncates around here; warn beyond it


# ---------------------------------------------------------------------------
# enum name for a param (kshep-side slot constant), e.g. reverb_time -> REVERB_TIME
# ---------------------------------------------------------------------------
def enum_name(rnbo_name):
    return rnbo_name.upper()


# ---------------------------------------------------------------------------
# header
# ---------------------------------------------------------------------------
def gen_header(class_name, snake, module_class, non_reserved):
    guard = f"{snake.upper()}_MODULE_H"
    rnbo_class = class_name  # RNBO export class name (== classname in export)

    # enum entries, one per non-reserved param, in slot order
    enum_lines = []
    for i, p in enumerate(non_reserved):
        enum_lines.append(f"        {enum_name(p['name'])} = {i},")
    enum_block = "\n".join(enum_lines)

    return f"""#pragma once
#ifndef {guard}
#define {guard}

// ===========================================================================
// {snake}_module.h  — GENERATED by make_effect.py. Do not hand-edit.
// ---------------------------------------------------------------------------
// Self-contained per-effect wrapper, same PIMPL shape as the proven freezeverb
// v12 wrapper. RNBO is NOT included here — only forward-declared — so this
// header can sit next to q-using modules in loaded_effects.h without the
// fast-math symbol clash. All RNBO access lives in {snake}_module.cpp.
// ===========================================================================

#include <stdint.h>
#include "base_effect_module.h"

#ifdef __cplusplus

// Forward declaration only — no RNBO headers here. The concrete type is named
// in {snake}_module.cpp, which includes the export first.
namespace RNBO {{
    template <class ENGINE> class {rnbo_class};
}}

namespace bkshepherd {{

class {module_class} : public BaseEffectModule {{
  public:
    // kshep-side param SLOTS (not RNBO indices). The RNBO index for each is
    // discovered by name at Init(). Order matches the s_metaData table and the
    // s_paramNames table in the .cpp. Generated from description.json.
    enum Param {{
{enum_block}
        PARAM_COUNT
    }};

    {module_class}();
    ~{module_class}();

    void Init(float sample_rate) override;
    void ProcessMono(float in) override;
    void ProcessStereo(float inL, float inR) override;
    float GetBrightnessForLED(int led_id) const override;
    void SetFootswitch(int fsw_id, float value) override;

    // RNBO effects use switch 1 as a raw footswitch (into fsw1), not framework
    // bypass. On/off lives in the patch.
    bool UsesRawFootswitch1() const override {{ return true; }}

  private:
    static constexpr int kBlockSize = 48; // must match guitar_pedal.cpp blockSize

    // Discovered RNBO indices for the reserved-name params (-1 = absent).
    int m_fsw1Index = -1;
    int m_fsw2Index = -1;
    int m_led1Index = -1;
    int m_led2Index = -1;

    // Discovered RNBO index per non-reserved param, indexed by the Param enum
    // slot above. Resolved by name at Init().
    int m_paramIndex[PARAM_COUNT];

    // Latest raw footswitch values (written by SetFootswitch on the main loop,
    // read by ProcessAudioBlock on the audio thread).
    volatile float m_fsw1Value = 0.0f;
    volatile float m_fsw2Value = 0.0f;

    // Cached LED values (written audio thread, read by the const UI getter).
    volatile float m_led1Value = 0.0f;
    volatile float m_led2Value = 0.0f;

    // sample<->block bridge state
    float m_inL[kBlockSize];
    float m_inR[kBlockSize];
    float m_outL[kBlockSize];
    float m_outR[kBlockSize];
    int m_bufferIndex;

    // RNBO engine, hidden behind an opaque pointer (PIMPL).
    struct Impl;
    Impl *m_impl;

    void ProcessAudioBlock(int size);
}};

}} // namespace bkshepherd
#endif // __cplusplus
#endif // {guard}
"""


# ---------------------------------------------------------------------------
# cpp
# ---------------------------------------------------------------------------
def gen_cpp(class_name, snake, module_class, non_reserved):
    rnbo_class = class_name

    # s_paramNames: exact RNBO names in slot order (for name discovery + push)
    name_rows = ",\n".join(f'    "{p["name"]}"' for p in non_reserved)

    # s_metaData: one ParameterMetaData per slot
    meta_rows = []
    for p in non_reserved:
        label = clean_label(p["name"])
        default = p.get("initialValue", 0.0)
        knob = p["knobMapping"]
        meta_rows.append(f"""    {{
        name : "{label}",
        valueType : ParameterValueType::Float,
        valueBinCount : 0,
        defaultValue : {{.float_value = {float(default)}f}},
        knobMapping : {knob},
        midiCCMapping : -1
    }}""")
    meta_block = ",\n".join(meta_rows)

    return f"""// ===========================================================================
// {snake}_module.cpp  — GENERATED by make_effect.py. Do not hand-edit.
// ---------------------------------------------------------------------------
// The ONE translation unit where RNBO is included. `q` must never be included
// here. Modeled on the proven freezeverb v12 wrapper, generalized from 3
// hardcoded knobs to a loop over the discovered param table.
// ===========================================================================

#include "{snake}_module.h"
#include <string.h> // strcmp for param-name discovery

// RNBO export, included under its NATIVE filename (RNBO writes "<classname>.cpp.h").
// Must sit at dependencies/RNBO/{snake}.cpp.h.
#include "{snake}.cpp.h"

using namespace bkshepherd;

// ---------------------------------------------------------------------------
// PIMPL: the concrete RNBO object and its non-interleaved buffer pointers.
// ---------------------------------------------------------------------------
struct {module_class}::Impl {{
    RNBO::{rnbo_class}<> rnbo;
    RNBO::SampleValue *in[2];
    RNBO::SampleValue *out[2];
}};

// ---------------------------------------------------------------------------
// Exact RNBO param names, in Param-enum slot order. Used to discover each
// param's RNBO index by name at Init(), and to know what to push each block.
// ---------------------------------------------------------------------------
static const char *s_paramNames[{module_class}::PARAM_COUNT] = {{
{name_rows}
}};

// ---------------------------------------------------------------------------
// kshep parameter metadata, same slot order. Labels cleaned from RNBO names;
// defaults from description.json initialValue; no MIDI CC yet (-1).
// ---------------------------------------------------------------------------
static const ParameterMetaData s_metaData[{module_class}::PARAM_COUNT] = {{
{meta_block}
}};

// ---------------------------------------------------------------------------
{module_class}::{module_class}() : BaseEffectModule(), m_bufferIndex(0), m_impl(nullptr) {{
    m_name = "{class_name}";

    m_paramMetaData = s_metaData;
    InitParams({module_class}::PARAM_COUNT);

    for (int i = 0; i < {module_class}::PARAM_COUNT; ++i) {{
        m_paramIndex[i] = -1;
    }}

    // RNBO object is NOT constructed here — deferred to Init() (module ctors run
    // very early, before hardware/heap are up; constructing RNBO that early can
    // fault on bare metal).
}}

{module_class}::~{module_class}() {{
    delete m_impl;
}}

void {module_class}::Init(float sample_rate) {{
    BaseEffectModule::Init(sample_rate);

    m_bufferIndex = 0;
    for (int i = 0; i < kBlockSize; ++i) {{
        m_inL[i] = 0.0f;
        m_inR[i] = 0.0f;
        m_outL[i] = 0.0f;
        m_outR[i] = 0.0f;
    }}

    if (m_impl == nullptr) {{
        m_impl = new Impl();
        m_impl->in[0] = m_inL;
        m_impl->in[1] = m_inR;
        m_impl->out[0] = m_outL;
        m_impl->out[1] = m_outR;
    }}

    m_impl->rnbo.initialize();
    m_impl->rnbo.prepareToProcess(sample_rate, kBlockSize, true);

    // Discovery: scan RNBO params by name. Reserved names -> fsw/led members;
    // everything else -> matched against s_paramNames and cached by slot.
    m_fsw1Index = m_fsw2Index = m_led1Index = m_led2Index = -1;
    for (int i = 0; i < {module_class}::PARAM_COUNT; ++i) {{
        m_paramIndex[i] = -1;
    }}

    const RNBO::ParameterIndex n = m_impl->rnbo.getNumParameters();
    for (RNBO::ParameterIndex i = 0; i < n; ++i) {{
        const char *pname = m_impl->rnbo.getParameterName(i);
        if (pname == nullptr) {{
            continue;
        }}
        if (strcmp(pname, "fsw1") == 0) {{
            m_fsw1Index = (int)i;
        }} else if (strcmp(pname, "fsw2") == 0) {{
            m_fsw2Index = (int)i;
        }} else if (strcmp(pname, "led1") == 0) {{
            m_led1Index = (int)i;
        }} else if (strcmp(pname, "led2") == 0) {{
            m_led2Index = (int)i;
        }} else {{
            for (int k = 0; k < {module_class}::PARAM_COUNT; ++k) {{
                if (strcmp(pname, s_paramNames[k]) == 0) {{
                    m_paramIndex[k] = (int)i;
                    break;
                }}
            }}
        }}
    }}

    // Push initial values (unconditional; matches v12).
    for (int k = 0; k < {module_class}::PARAM_COUNT; ++k) {{
        if (m_paramIndex[k] >= 0) {{
            m_impl->rnbo.setParameterValue(m_paramIndex[k], GetParameterAsFloat(k), RNBO::TimeNow);
        }}
    }}
}}

// ---------------------------------------------------------------------------
void {module_class}::ProcessAudioBlock(int size) {{
    // Push all params (unconditional every block, matches v12).
    for (int k = 0; k < {module_class}::PARAM_COUNT; ++k) {{
        if (m_paramIndex[k] >= 0) {{
            m_impl->rnbo.setParameterValue(m_paramIndex[k], GetParameterAsFloat(k), RNBO::TimeNow);
        }}
    }}

    // Footswitch state -> discovered fsw params (audio thread).
    if (m_fsw1Index >= 0) {{
        m_impl->rnbo.setParameterValue(m_fsw1Index, m_fsw1Value, RNBO::TimeNow);
    }}
    if (m_fsw2Index >= 0) {{
        m_impl->rnbo.setParameterValue(m_fsw2Index, m_fsw2Value, RNBO::TimeNow);
    }}

    m_impl->rnbo.process(m_impl->in, 2, m_impl->out, 2, (RNBO::Index)size);

    // Cache LED values the patch computed, for the const LED getter.
    if (m_led1Index >= 0) {{
        m_led1Value = (float)m_impl->rnbo.getParameterValue(m_led1Index);
    }}
    if (m_led2Index >= 0) {{
        m_led2Value = (float)m_impl->rnbo.getParameterValue(m_led2Index);
    }}
}}

// ---------------------------------------------------------------------------
void {module_class}::SetFootswitch(int fsw_id, float value) {{
    if (fsw_id == 0) {{
        m_fsw1Value = value;
    }} else if (fsw_id == 1) {{
        m_fsw2Value = value;
    }}
}}

// ---------------------------------------------------------------------------
void {module_class}::ProcessStereo(float inL, float inR) {{
    if (m_impl == nullptr) {{
        m_audioLeft = inL;
        m_audioRight = inR;
        return;
    }}

    m_inL[m_bufferIndex] = inL;
    m_inR[m_bufferIndex] = inR;

    m_audioLeft = m_outL[m_bufferIndex];
    m_audioRight = m_outR[m_bufferIndex];

    ++m_bufferIndex;
    if (m_bufferIndex >= kBlockSize) {{
        ProcessAudioBlock(kBlockSize);
        m_bufferIndex = 0;
    }}
}}

void {module_class}::ProcessMono(float in) {{
    ProcessStereo(in, in);
}}

// ---------------------------------------------------------------------------
float {module_class}::GetBrightnessForLED(int led_id) const {{
    if (m_impl != nullptr) {{
        if (led_id == 0 && m_led1Index >= 0) {{
            return m_led1Value;
        }}
        if (led_id == 1 && m_led2Index >= 0) {{
            return m_led2Value;
        }}
    }}
    return BaseEffectModule::GetBrightnessForLED(led_id);
}}
"""


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    export_folder = sys.argv[1]
    out_folder = sys.argv[2]
    data = load_description(export_folder)
    meta = data.get("meta", {})

    class_name = sys.argv[3] if len(sys.argv) > 3 else meta.get("rnboobjname", "Effect")
    snake = sys.argv[4] if len(sys.argv) > 4 else meta.get("name", "effect")
    module_class = f"{class_name}Module"

    params = data["parameters"]
    non_reserved, knobs, menu, overflow = classify(params)

    # attach knobMapping to each non-reserved param (knob slot or -1)
    for slot, p in enumerate(non_reserved):
        p["knobMapping"] = slot if slot < MAX_KNOBS else -1

    # warnings
    warnings = []
    if overflow:
        warnings.append(f"{len(overflow)} param(s) beyond 16 non-reserved capacity "
                        f"-> DROPPED: {', '.join(p['name'] for p in overflow)}")
    for p in non_reserved:
        label = clean_label(p["name"])
        if len(label) > LABEL_WARN_LEN:
            warnings.append(f"label '{label}' ({len(label)} chars) may truncate on screen")

    os.makedirs(out_folder, exist_ok=True)
    h_path = os.path.join(out_folder, f"{snake}_module.h")
    c_path = os.path.join(out_folder, f"{snake}_module.cpp")

    with open(h_path, "w") as f:
        f.write(gen_header(class_name, snake, module_class, non_reserved))
    with open(c_path, "w") as f:
        f.write(gen_cpp(class_name, snake, module_class, non_reserved))

    print("=" * 60)
    print("  make_effect  STAGE 2 — module-file generator")
    print("=" * 60)
    print(f"  class name    : {class_name}")
    print(f"  module class  : {module_class}")
    print(f"  file stem     : {snake}")
    print(f"  params        : {len(non_reserved)} non-reserved "
          f"({len(knobs)} knob, {len(menu)} menu)")
    print(f"  wrote         : {h_path}")
    print(f"                  {c_path}")
    if warnings:
        print("  WARNINGS:")
        for w in warnings:
            print(f"    ! {w}")
    print("=" * 60)


if __name__ == "__main__":
    main()
